updates to build pmac on rtems

diff --git a/build b/build
--- a/build
+++ b/build
@@ -17,11 +17,16 @@ set -xe
 cd $(dirname ${0})
 
 # use docker if available else use podman
-if ! docker version &>/dev/null; then alias docker=podman; fi
+if ! docker version &>/dev/null; then docker=podman; else docker=docker; fi
+
+if ! $docker buildx version &>/dev/null; then
+    echo "buildx required. (install with 'apt install docker-buildx')"
+    exit 1
+fi
 
 # make sure new repos get their submodule ibek-support
 git submodule update --init
 
 # build and developer images
-docker build -t ${TAG} --build-arg TARGET_ARCHITECTURE=$T_A --target $TARGET .
+$docker buildx build -t ${TAG} --build-arg TARGET_ARCHITECTURE=$T_A --target $TARGET .
 
